### ISSUE TITLE
Where to insert google api key?

### ISSUE THREAD

**Issue by eraframework** [mustafababil/Taxi-Fare-on-Map#1]
Where to insert google api key. and also included js file link through 404 error  "https://code.google.com/apis/gears/gears_init.js"

**Comment by mustafababil** [comment]
If you want to use Google Maps API with your key, you can change [line 19 in index.html](https://github.com/mustafababil/Taxi-Fare-on-Map/blob/master/index.html#L19) with `<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY></script>`

gears_init.js part is deleted as it is not used throughout the project.

Thanks.
